### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#123]
```Traceback (most recent call last):
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>
    sys.exit(TargetPostgres.cli())
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 572, in cli
    target.listen(file_input)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 34, in listen
    self._process_lines(file_input)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 272, in _process_lines
    counter = super()._process_lines(file_input)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 81, in _process_lines
    self._process_record_message(line_dict)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target.py", line 166, in _process_record_message
    super()._process_record_message(message_dict)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 315, in _process_record_message
    sink._validate_and_parse(transformed_record)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/sinks/core.py", line 302, in _validate_and_parse
    self._validator.validate(record)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 313, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/_validators.py", line 321, in type
    if not any(validator.is_type(instance, type) for type in types):
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/_validators.py", line 321, in <genexpr>
    if not any(validator.is_type(instance, type) for type in types):
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/validators.py", line 318, in is_type
    return self.TYPE_CHECKER.is_type(instance, type)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/jsonschema/_types.py", line 117, in is_type
    fn = self._type_checkers[type]
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/pyrsistent/_pmap.py", line 169, in __getitem__
    return PMap._getitem(self._buckets, key)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/pyrsistent/_pmap.py", line 160, in _getitem
    _, bucket = PMap._get_bucket(buckets, key)
  File "/home/visch/git/tap-indeed/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/pyrsistent/_pmap.py", line 154, in _get_bucket
    index = hash(key) % len(buckets)
TypeError: unhashable type: 'list'```

**Comment by visch** [comment]
Hard to find out what stream is causing this. Should be easier to find, not certain if this is a tap bug / target bug yet.

**Comment by visch** [comment]
Can't reproduce, closing
