### ISSUE TITLE
pre-commit Fails due to version

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#130]
```
annotations==2.9.0,flake8-docstrings==1.6.0](https://github.com/pycqa/flake8:darglint==1.8.1,flake8-annotations==2.9.0,flake8-docstrings==1.6.0).
[INFO] Initializing environment for [https://github.com/asottile/pyupgrade](https://github.com/asottile/pyupgrade).
[INFO] Installing environment for [https://github.com/pre-commit/pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks).
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for [https://github.com/psf/black](https://github.com/psf/black).
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for [https://github.com/pycqa/isort](https://github.com/pycqa/isort).
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repomm4f8at5/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /root/.cache/pre-commit/repomm4f8at5
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/root/.cache/pre-commit/repomm4f8at5/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/root/.cache/pre-commit/repomm4f8at5/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/root/.cache/pre-commit/repomm4f8at5/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-4z5dkc5p/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-4z5dkc5p/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 58, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

Maybe we can get pre-commit to auto update with Dependabot as well? Upgrading to 5.12.0 for isort fixes this re  https://github.com/home-assistant/core/issues/86892

**Comment by edgarrmondragon** [comment]
@visch pre-commit should've been getting hook auto-updates, but pre-commit.ci was not enabled for this repo 🤦‍♂️. I just did, so you should see a PR in the next days.

**Comment by visch** [comment]
> @visch pre-commit should've been getting hook auto-updates, but pre-commit.ci was not enabled for this repo 🤦‍♂️. I just did, so you should see a PR in the next days.

Nice!! Thank you @edgarrmondragon  no issue :D

**Comment by edgarrmondragon** [comment]
See https://github.com/MeltanoLabs/target-postgres/pull/134
