### ISSUE TITLE
Alter table seems to fail when target table is upper case

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#151]
See https://meltano.slack.com/archives/C01TCRBBJD7/p1687708542932649

Logs

```
❯ meltano run tap-oracle target-postgres
2023-06-25T15:38:53.225090Z [info     ] Environment 'dev' is active
2023-06-25T15:38:58.650157Z [warning  ] No state was found, complete import.
2023-06-25T15:38:58.807022Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=Selected streams: ['MY_ORACLE_SCHEMA-MY_TABLE'] cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.807341Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=No currently_syncing found cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.807488Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=Beginning sync of stream(MY_ORACLE_SCHEMA-MY_TABLE) with sync method(full) cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.807680Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=Stream MY_ORACLE_SCHEMA-MY_TABLE is using full_table replication cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.807773Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=dsn: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=redacted)(PORT=redacted))(CONNECT_DATA=(SERVICE_NAME=redacted))) cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.903584Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=select SELECT  "REDACTED_1" , "REDACTED_2" ORA_ROWSCN cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.903761Z [info     ]                                 FROM MY_ORACLE_SCHEMA.MY_TABLE cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.903854Z [info     ]                                ORDER BY ORA_ROWSCN ASC cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.917362Z [info     ] time=2023-06-25 17:38:58 name=singer level=INFO message=METRIC: b'{"type":"counter","metric":"record_count","value":150,"tags":{}}' cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-25T15:38:58.932686Z [info     ] time=2023-06-25 17:38:58 name=target_postgres level=INFO message=Table '"my_table"' exists cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.954964Z [info     ] time=2023-06-25 17:38:58 name=target_postgres level=INFO message=Versioning column: ALTER TABLE source."my_table" RENAME COLUMN "redacted" TO "redacted_20230625_1738" cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964216Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964346Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module> cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964597Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964690Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/__init__.py", line 373, in main cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964755Z [info     ]     persist_lines(config, singer_messages) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964840Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/__init__.py", line 219, in persist_lines cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.964982Z [info     ]     stream_to_sync[stream].sync_table() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965074Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/db_sync.py", line 594, in sync_table cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965484Z [info     ]     self.update_columns()      cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965554Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/db_sync.py", line 560, in update_columns cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965614Z [info     ]     self.version_column(column_name, stream) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965667Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/db_sync.py", line 574, in version_column cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965729Z [info     ]     self.query(version_column) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965794Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/db_sync.py", line 311, in query cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965881Z [info     ]     cur.execute(               cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965940Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/psycopg2/extras.py", line 146, in execute cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.966073Z [info     ]     return super().execute(query, vars) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.966172Z [info     ] psycopg2.errors.UndefinedTable: relation "source.my_table" does not exist cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.966258Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.990468Z [error    ] Loader failed
2023-06-25T15:38:58.990711Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
2023-06-25T15:39:02.189723Z [error    ] Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, 'Broken pipe')> 
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /redacted/.pyenv/versions/3.10.11/lib/python3.10/asyncio/unix_events.py:698 in           │
│ _write_ready                                                                                     │
│                                                                                                  │
│    695 │   │   assert self._buffer, 'Data should not be empty'                                   │
│    696 │   │                                                                                     │
│    697 │   │   try:                                                                              │
│ ❱  698 │   │   │   n = os.write(self._fileno, self._buffer)                                      │
│    699 │   │   except (BlockingIOError, InterruptedError):                                       │
│    700 │   │   │   pass                                                                          │
│    701 │   │   except (SystemExit, KeyboardInterrupt):                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by visch** [comment]
This stack trace is from a different postgres variant.
```
2023-06-25T15:38:58.965794Z [info     ]   File "/radacted/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/db_sync.py", line 311, in query cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-25T15:38:58.965881Z [info     ]     
```

db_sync doesn't exist in this variant
