### ISSUE TITLE
Schema containing properties without a type cause an error

### ISSUE THREAD

**Issue by andyoneal** [MeltanoLabs/target-postgres#168]
Apparently, type is not required in json schema, but target-postgres throws the error: `RuntimeError: Neither type nor anyOf are present. Unable to determine type.`

I'm not sure how common this is, or what the target should do in that situation (cast to string?), but I believe if type is not present in the schema, it's valid for any type. I ran into this using [tap-salesforce](https://github.com/meltanolabs/tap-salesforce) because salesforce has a few system/internal objects that have [fields with type "anyType"](https://github.com/MeltanoLabs/tap-salesforce/blob/d802f68929d9621a72a9639603b422ea90490520/tap_salesforce/salesforce/__init__.py#L174).

See `OldValue` and `NewValue` in the schema below.

```
{"type": "SCHEMA", "stream": "Tenant__History", "schema": {"type": "object", "additionalProperties": false, "properties": {"Id": {"type": "string"}, "IsDeleted": {"type": ["null", "boolean"]}, "ParentId": {"type": ["null", "string"]}, "CreatedById": {"type": ["null", "string"]}, "CreatedDate": {"anyOf": [{"type": "string", "format": "date-time"}, {"type": ["string", "null"]}]}, "Field": {"type": ["null", "string"]}, "DataType": {"type": ["null", "string"]}, "OldValue": {}, "NewValue": {}}}, "key_properties": ["Id"], "bookmark_properties": ["CreatedDate"]}

Traceback (most recent call last):
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>
    sys.exit(TargetPostgres.cli())
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)     
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 546, in invoke
    target.listen(file_input) 
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 33, in listen
    self._process_lines(file_input)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 291, in _process_lines
    counter = super()._process_lines(file_input)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 76, in _process_lines
    self._process_schema_message(line_dict)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target.py", line 349, in _process_schema_message
    super()._process_schema_message(message_dict)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 399, in _process_schema_message
    _ = self.get_sink(        
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 167, in get_sink
    return self.add_sink(stream_name, schema, key_properties)
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 248, in add_sink
    sink.setup()              
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/sinks.py", line 50, in setup
    self.connector.prepare_table(
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/connector.py", line 119, in prepare_table
    sql_type=self.to_sql_type(property_def),
  File "/home/azureuser/datawarehouse/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/connector.py", line 241, in to_sql_type
    raise RuntimeError(msg)   
RuntimeError: Neither type nor anyOf are present. Unable to determine type.
```

**Comment by visch** [comment]
hmm do we just support this kind of thing or push it back to the tap? I don't think this follows the singer spec.

Maybe we should support it? I'm not sure! I'll ask about sorry for the delayed respond

**Comment by andyoneal** [comment]
As far as I could tell, the singer spec requires a valid json schema, and json schema does not require type or anyof. If that's true, I think the target should handle it somehow.

I'm not sure how else you would support it besides defaulting to string. Feels inelegant, but what else can you do?

**Comment by visch** [comment]
> As far as I could tell, the singer spec requires a valid json schema, and json schema does not require type or anyof. If that's true, I think the target should handle it somehow.
> 
> I'm not sure how else you would support it besides defaulting to string. Feels inelegant, but what else can you do?

Yeah I was thinking just don't support it is one option, but just converting it to a string seems like an easy enough option, but to me I really think think the tap should pick not the target. Haven't seen this in any tap myself, but we can support it I guess!

**Comment by andyoneal** [comment]
> Yeah I was thinking just don't support it is one option, but just converting it to a string seems like an easy enough option, but to me I really think think the tap should pick not the target. Haven't seen this in any tap myself, but we can support it I guess!

In a perfect world, I'd agree. It should be the tap that figures this out. But at the very least, this is a grey area of the Singer spec. This is a Meltano-built tap forked from singer-io's official tap. If it's doing this "no type" thing, I would guess there are others.

Just realized I linked the singer-io variant of tap-salesforce. To be clear, I'm using the meltanolabs tap-salesforce and seeing this behavior.
