### ISSUE TITLE
tap-googleads failure

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#23]
Haven't dove but here's the error
```
2022-11-02T19:47:11.688962Z [info     ] 2022-11-02 15:47:11,688 Inserting with SQL: INSERT INTO temp_402193f8_b54d_4076_8e33_d256edcacf32 (_sdc_primary_key, geo_target_constant) VALUES (:_sdc_primary_key, :geo_target_constant) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744059Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744302Z [info     ]   File "/home/visch/git/tap-googleads/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744424Z [info     ]     self.dialect.do_execute(   cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744561Z [info     ]   File "/home/visch/git/tap-googleads/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744702Z [info     ]     cursor.execute(statement, parameters) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744838Z [info     ] psycopg2.errors.UndefinedColumn: column temp.geotargetconstant does not exist cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.744973Z [info     ] LINE 3: ...mary_key=temp._sdc_primary_key, geoTargetConstant=temp.geoTa... cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745122Z [info     ]                                                              ^ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745257Z [info     ] HINT:  Perhaps you meant to reference the column "temp.geo_target_constant" or the column "temp.geoTargetConstant". cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745394Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745529Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745664Z [info     ] The above exception was the direct cause of the following exception: cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745798Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.745932Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.746082Z [info     ]   File "/home/visch/git/tap-googleads/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module> cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2022-11-02T19:47:11.746242Z [info     ]     sys.exit(TargetPostgres.cli()) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres                                                                                                                                                                                       
```

**Comment by visch** [comment]
This is fixed, we have a new one I'll put a seperate issue in
