### ISSUE TITLE
(psycopg2.errors.DuplicateColumn) column ... of relation ... already exists

### ISSUE THREAD

**Issue by chrislondon** [MeltanoLabs/target-postgres#314]
I'm successfully using this target with the `tap-quickbooks` but when piping the `tap-hubspot` to `target-postgres` is giving me this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "property_hs_time_to_move_from_marketingqualifiedlead_to_custome" of relation "contacts" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/venvs/target-postgres/bin/target-postgres", line 8, in <module>
    sys.exit(TargetPostgres.cli())
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/plugin_base.py", line 80, in invoke
    return super().invoke(ctx)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/target_base.py", line 565, in invoke
    target.listen(file_input)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen
    self._process_lines(file_input)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/target_base.py", line 306, in _process_lines
    counter = super()._process_lines(file_input)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/io_base.py", line 91, in _process_lines
    self._process_schema_message(line_dict)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/target_base.py", line 418, in _process_schema_message
    _ = self.get_sink(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/target_base.py", line 789, in get_sink
    return self.add_sqlsink(stream_name, schema, key_properties)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/singer_sdk/target_base.py", line 723, in add_sqlsink
    sink.setup()
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/target_postgres/sinks.py", line 57, in setup
    self.connector.prepare_table(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/target_postgres/connector.py", line 146, in prepare_table
    self.prepare_column(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/target_postgres/connector.py", line 417, in prepare_column
    self._create_empty_column(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/target_postgres/connector.py", line 467, in _create_empty_column
    connection.execute(column_add_ddl)
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1532, in _execute_ddl
    ret = self._execute_context(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/venvs/target-postgres/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateColumn) column "property_hs_time_to_move_from_marketingqualifiedlead_to_custome" of relation "contacts" already exists

[SQL: ALTER TABLE "hs"."contacts"ADD COLUMN property_hs_time_to_move_from_marketingqualifiedlead_to_customer JSONB]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by chrislondon** [comment]
I believe the problem stems from ridiculously long column names.  I'm unable to change the data in Hubspot.  Is there a way to improve this `target-postgres` to be able to handle ridiculously long column names?

**Comment by visch** [comment]
There is a bug here in my opinion as Postgres should fail (I think?) for columns that are over a certain length as instead we give you this error if another column also matches this length.

@chrislondon  it's a postgres limitation, you can recompile your postgres instance.

The easier fix is to manually map those columns to different names using stream maps https://sdk.meltano.com/en/latest/stream_maps.html#constructing-the-stream-maps-config-object
